'''
Author: doumeng1026@gmail.com
Date: 2026-04-27 10:28:04
LastEditors: Do not edit
LastEditTime: 2026-05-13 18:08:31
Description:
FilePath: \v3\config.py
'''
# Configuration File
# ------------------
# Define constants and default values here.

import struct

# Network
DEFAULT_IP = "0.0.0.0"
DEFAULT_PORT = 10000

# Data Protocol
IMG_WIDTH = 128
IMG_HEIGHT = 128
PIXEL_COUNT = IMG_WIDTH * IMG_HEIGHT


BYTES_PER_PIXEL = 4
FRAME_PAYLOAD_SIZE = PIXEL_COUNT * BYTES_PER_PIXEL


# Protocol Constants (Confirmed)
PACKET_HEADER = b'\x55\xaa'  # Little-endian or Big-endian? 0xAA55 usually means 0x55 then 0xAA if little-endian. Let's assume network order.
# User said "1~2 帧头 START 0XAA55".
# Let's assume standard network byte order (Big Endian) for now unless specified.
# struct.unpack('>H') -> 0xAA55. So bytes would be \xaa\x55.

# Packet Structure Offsets (0-indexed)
OFFSET_START = 0
OFFSET_CONTROL = 2
OFFSET_TASK_ID = 4
OFFSET_TYPE = 7
OFFSET_SEQ = 8
OFFSET_PITCH = 9
OFFSET_YAW = 11
OFFSET_DATA = 13
DATA_LEN = 4096
OFFSET_FCS = OFFSET_DATA + DATA_LEN
OFFSET_END = OFFSET_DATA + DATA_LEN + 1

PACKET_SIZE = OFFSET_END + 2 # 4108 bytes

# Task Types
TASK_TYPE_INTENSITY_RANGE = 0
TASK_TYPE_TOF = 1

# Intensity/Range data formats
DATA_FORMAT_PREPROCESS = "preprocess"
DATA_FORMAT_INFO_BOARD = "info_board"
DEFAULT_DATA_FORMAT = DATA_FORMAT_INFO_BOARD

# Debug
RECEIVER_DEBUG = False

# Fragment Count
TOTAL_FRAGMENTS = 16 # 65536 / 4096
TOF_TOTAL_FRAGMENTS = 16

# Runtime Safety Limits
REASSEMBLY_TTL_SEC = 2.0
REASSEMBLY_CLEANUP_INTERVAL_SEC = 0.5
REASSEMBLY_MAX_TASKS = 512

RECORDER_QUEUE_MAXSIZE = 256
RECORDER_DROP_OLDEST = True

SERIAL_LOG_MAX_BLOCKS = 2000
HIST_UPDATE_INTERVAL_SEC = 0.5
DISPLAY_FLUSH_INTERVAL_MS = 16
DIAG_UPDATE_INTERVAL_SEC = 1.0

# Scaling Factors
RANGE_SCALE_FACTOR = 10.0  # Real Value = Raw / 10.0
INTENSITY_MAX_VAL = 200    # Expected max intensity value

# UI Defaults
DEFAULT_INTENSITY_CMAP = None
DEFAULT_RANGE_CMAP = 'jet'
DEFAULT_TOF_CMAP = 'plasma'

# Scene reconstruction defaults for 2-DoF lidar model
SCENE_RECON_MAX_RANGE_M = 5000.0
SCENE_RECON_LIDAR_H_FOV_DEG = 1.0
SCENE_RECON_LIDAR_V_FOV_DEG = 1.0
SCENE_RECON_FRAME_STRIDE = 25
SCENE_RECON_SERVO_LAG_FRAMES = 0
SCENE_RECON_FORWARD_AXIS = 'Z'

# Scene reconstruction ICP fine registration
SCENE_RECON_ICP_ENABLED = True
SCENE_RECON_ICP_VOXEL_SIZE = 0.25
SCENE_RECON_ICP_MAX_CORR_DIST = 0.8
SCENE_RECON_ICP_MAX_ITERATIONS = 80
SCENE_RECON_ICP_MIN_FITNESS = 0.12
SCENE_RECON_ICP_EVERY_N_FRAMES = 1
SCENE_RECON_ICP_MAP_WINDOW_FRAMES = 25
SCENE_RECON_ICP_MIN_POINTS = 200
SCENE_RECON_ICP_PRIOR_WEIGHT = 0.7
SCENE_RECON_ICP_MAX_DELTA_ROT_DEG = 2.5
SCENE_RECON_ICP_MAX_DELTA_TRANS_M = 0.25
SCENE_RECON_ICP_REJECT_DELTA_ROT_DEG = 8.0
SCENE_RECON_ICP_REJECT_DELTA_TRANS_M = 0.8
